#!/bin/sh
# Renders PKGBUILD and .SRCINFO for a published release.
#
#   packaging/aur/render.sh 2.7.0 [output-directory]
#
# The checksums are taken from the release's own `.sha256` files rather than
# recomputed, so the package verifies exactly what the Release workflow
# published. If an archive is missing the script fails instead of writing a
# PKGBUILD with a placeholder in it — an AUR package that fails to verify is
# worse than no update at all.
#
# `.SRCINFO` is generated by hand rather than with `makepkg --printsrcinfo`,
# because this runs on a GitHub runner where makepkg does not exist. The format
# is simple and stable; what matters is that it stays in step with PKGBUILD,
# which is why both come from the same three values.
set -eu

version=${1:-}
out=${2:-.}
if [ -z "$version" ]; then
    echo "usage: render.sh <version> [output-directory]" >&2
    exit 2
fi

here=$(cd "$(dirname "$0")" && pwd)
repo=${GITHUB_REPOSITORY:-LightZirconite/instaCache}
base="https://github.com/${repo}/releases/download/v${version}"

# The published checksum file is one line: "<sha256>  <filename>".
checksum() {
    arch=$1
    url="${base}/instacache-${version}-linux-${arch}.tar.gz.sha256"
    line=$(curl -fsSL --retry 3 --retry-delay 5 "$url") || {
        echo "render.sh: no checksum published at $url" >&2
        exit 1
    }
    sum=$(printf '%s\n' "$line" | awk 'NR==1 {print $1}')
    case "$sum" in
        ????????????????????????????????????????????????????????????????) ;;
        *)
            echo "render.sh: $url did not contain a sha256 (got '$sum')" >&2
            exit 1
            ;;
    esac
    printf '%s' "$sum"
}

x86_64=$(checksum x86_64)
aarch64=$(checksum aarch64)

mkdir -p "$out"
sed \
    -e "s|@VERSION@|${version}|g" \
    -e "s|@SHA256_X86_64@|${x86_64}|g" \
    -e "s|@SHA256_AARCH64@|${aarch64}|g" \
    "$here/PKGBUILD.in" > "$out/PKGBUILD"

cat > "$out/.SRCINFO" <<EOF
pkgbase = instacache-bin
	pkgdesc = Ultra-light native Instagram desktop client, with a persistent cache and desktop notifications
	pkgver = ${version}
	pkgrel = 1
	url = https://github.com/${repo}
	arch = x86_64
	arch = aarch64
	license = AGPL-3.0-or-later
	depends = qt6-base
	depends = qt6-declarative
	depends = qt6-webengine
	depends = hicolor-icon-theme
	optdepends = libcanberra: sounds for notifications and for an incoming call
	optdepends = sound-theme-freedesktop: the sounds themselves
	optdepends = libappindicator-gtk3: tray icon on desktops without native StatusNotifier support
	provides = instacache=${version}
	conflicts = instacache
	conflicts = instacache-git
	options = !strip
	options = !debug
	source_x86_64 = instacache-${version}-x86_64.tar.gz::${base}/instacache-${version}-linux-x86_64.tar.gz
	sha256sums_x86_64 = ${x86_64}
	source_aarch64 = instacache-${version}-aarch64.tar.gz::${base}/instacache-${version}-linux-aarch64.tar.gz
	sha256sums_aarch64 = ${aarch64}

pkgname = instacache-bin
EOF

echo "Rendered $out/PKGBUILD and $out/.SRCINFO for ${version}"
echo "  x86_64  ${x86_64}"
echo "  aarch64 ${aarch64}"
